CREATE DATABASE IF NOT EXISTS telemetry;

-- Logs table
CREATE TABLE IF NOT EXISTS telemetry.logs (
    deployment_id String,
    timestamp DateTime64(3, 'UTC'),
    level Enum('debug' = 1, 'info' = 2, 'warn' = 3, 'error' = 4),
    message String,
    metadata JSON,
    tenant_id String,
    PRIMARY KEY (deployment_id, timestamp)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (deployment_id, timestamp);

-- Metrics table
CREATE TABLE IF NOT EXISTS telemetry.metrics (
    deployment_id String,
    timestamp DateTime64(3, 'UTC'),
    metric_name String,
    metric_value Float64,
    tags JSON,
    tenant_id String,
    PRIMARY KEY (deployment_id, metric_name, timestamp)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (deployment_id, metric_name, timestamp);

-- Traces table
CREATE TABLE IF NOT EXISTS telemetry.traces (
    trace_id String,
    span_id String,
    parent_span_id String,
    deployment_id String,
    timestamp DateTime64(3, 'UTC'),
    duration_ms UInt64,
    name String,
    status Enum('ok' = 1, 'error' = 2),
    attributes JSON,
    tenant_id String,
    PRIMARY KEY (trace_id, span_id)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (trace_id, span_id);

-- Events table (deployment events, payments, etc.)
CREATE TABLE IF NOT EXISTS telemetry.events (
    event_id UUID,
    deployment_id String,
    timestamp DateTime64(3, 'UTC'),
    event_type String,
    payload JSON,
    tenant_id String,
    PRIMARY KEY (event_id)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(timestamp)
ORDER BY (timestamp);

-- AI Insights table
CREATE TABLE IF NOT EXISTS telemetry.ai_insights (
    insight_id UUID,
    deployment_id String,
    timestamp DateTime64(3, 'UTC'),
    insight_type String,
    content JSON,
    severity Enum('info' = 1, 'warning' = 2, 'critical' = 3),
    payload JSON
) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (deployment_id, event_type, timestamp);

-- Payments analytics
CREATE TABLE IF NOT EXISTS finance.payments (
    timestamp DateTime64(3) DEFAULT now(),
    payment_id String,
    user_id String,
    amount Decimal(18,4),
    currency String,
    status Enum8('SUCCESS' = 1, 'FAILED' = 2, 'REFUNDED' = 3),
    provider String,
    metadata JSON
) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (payment_id);

-- AI insights (generated by AI layer)
CREATE TABLE IF NOT EXISTS ai.insights (
    timestamp DateTime64(3) DEFAULT now(),
    deployment_id String,
    insight_id String,
    type Enum8('ANOMALY' = 1, 'RECOMMENDATION' = 2, 'ROOT_CAUSE' = 3),
    title String,
    description String,
    severity Enum8('LOW' = 1, 'MEDIUM' = 2, 'HIGH' = 3),
    payload JSON
) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (deployment_id, insight_id);


-- Aggregated metrics table
CREATE TABLE IF NOT EXISTS telemetry.metrics_agg (
    deployment_id String,
    minute DateTime64(3, 'UTC'),
    metric_name String,
    max_value Float64,
    min_value Float64,
    samples UInt64,
    PRIMARY KEY (deployment_id, minute, metric_name)
) ENGINE = MergeTree()
PARTITION BY toYYYYMM(minute)
ORDER BY (deployment_id, minute, metric_name);

-- Materialized view for aggregated metrics (e.g., avg latency per deployment per minute)
CREATE MATERIALIZED VIEW IF NOT EXISTS telemetry.metric_aggregates TO telemetry.metrics_agg AS
SELECT
    deployment_id,
    toStartOfMinute(timestamp) AS minute,
    metric_name,
    max(metric_value) AS max_value,
    min(metric_value) AS min_value,
    count() AS samples
FROM telemetry.metrics
GROUP BY deployment_id, minute, metric_name;
