from enum import Enum, auto

class SystemState(Enum):
    IDLE = "IDLE"
    IDEA_GENERATION = "IDEA_GENERATION"
    RESEARCH = "RESEARCH"
    BUSINESS_PLAN_PRD = "BUSINESS_PLAN_PRD"
    MVP_BUILD = "MVP_BUILD"
    DEPLOYMENT = "DEPLOYMENT"
    MONITORING = "MONITORING"
    DECISION = "DECISION"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"
    TERMINATED = "TERMINATED"

class ExecutionContext(Enum):
    PLANNING = "PLANNING"
    BUILDING = "BUILDING"
    VERIFYING = "VERIFYING"
